Repository Ajou-Hertz/hertz-backend, pull requests merged in 2024-02, with the labels that each got.

#2 Swagger 설정 파일 작성
  build.gradle
  src/main/java/com/ajou/hertz/global/config/SwaggerConfig.java
  src/main/resources/application.properties
Labels: chore

#4 Logging 시스템 구축
  src/main/java/com/ajou/hertz/global/config/WebFilterConfig.java
  src/main/java/com/ajou/hertz/global/logger/Logger.java
  src/main/java/com/ajou/hertz/global/logger/aop/LogTrace.java
  src/main/java/com/ajou/hertz/global/logger/aop/LogTraceAspect.java
  src/main/java/com/ajou/hertz/global/logger/aop/Pointcuts.java
  src/main/java/com/ajou/hertz/global/logger/aop/TraceId.java
  src/main/java/com/ajou/hertz/global/logger/aop/TraceStatus.java
  src/main/java/com/ajou/hertz/global/logger/filter/LogApiInfoFilter.java
  src/main/java/com/ajou/hertz/global/logger/filter/RequestWrapper.java
  src/main/java/com/ajou/hertz/global/logger/filter/ResponseWrapper.java
  src/main/java/com/ajou/hertz/global/logger/util/LogTraceUtils.java
Labels: enhancement

#6 Exception handling 시스템 구축
  src/main/java/com/ajou/hertz/global/common/exception/BadRequestException.java
  src/main/java/com/ajou/hertz/global/common/exception/ConflictException.java
  src/main/java/com/ajou/hertz/global/common/exception/CustomException.java
  src/main/java/com/ajou/hertz/global/common/exception/ForbiddenException.java
  src/main/java/com/ajou/hertz/global/common/exception/InternalServerException.java
  src/main/java/com/ajou/hertz/global/common/exception/NotFoundException.java
  src/main/java/com/ajou/hertz/global/common/exception/UnauthorizedException.java
  src/main/java/com/ajou/hertz/global/common/exception/UnprocessableEntityException.java
  src/main/java/com/ajou/hertz/global/exception/GlobalExceptionHandler.java
  src/main/java/com/ajou/hertz/global/exception/constant/CustomExceptionType.java
  src/main/java/com/ajou/hertz/global/exception/constant/GlobalExceptionType.java
  src/main/java/com/ajou/hertz/global/exception/constant/ValidationErrorCode.java
  src/main/java/com/ajou/hertz/global/exception/dto/response/ErrorResponse.java
  src/main/java/com/ajou/hertz/global/exception/dto/response/ValidationErrorDetailResponse.java
  src/main/java/com/ajou/hertz/global/exception/dto/response/ValidationErrorResponse.java
  src/main/java/com/ajou/hertz/global/exception/util/ExceptionUtils.java
  src/main/java/com/ajou/hertz/global/exception/util/ViolationMessageResolver.java
Labels: enhancement

#9 회원가입 API 구현
  src/main/java/com/ajou/hertz/domain/user/constant/Gender.java
  src/main/java/com/ajou/hertz/domain/user/controller/UserControllerV1.java
  src/main/java/com/ajou/hertz/domain/user/dto/UserDto.java
  src/main/java/com/ajou/hertz/domain/user/dto/request/SignUpRequest.java
  src/main/java/com/ajou/hertz/domain/user/dto/response/UserResponse.java
  src/main/java/com/ajou/hertz/domain/user/entity/User.java
  src/main/java/com/ajou/hertz/domain/user/exception/UserEmailDuplicationException.java
  src/main/java/com/ajou/hertz/domain/user/repository/UserRepository.java
  src/main/java/com/ajou/hertz/domain/user/service/UserCommandService.java
  src/main/java/com/ajou/hertz/domain/user/service/UserQueryService.java
  src/main/java/com/ajou/hertz/global/common/constant/GlobalConstants.java
  src/main/java/com/ajou/hertz/global/common/entity/BaseEntity.java
  src/main/java/com/ajou/hertz/global/common/entity/TimeTrackedBaseEntity.java
  src/main/java/com/ajou/hertz/global/config/JpaConfig.java
  src/main/java/com/ajou/hertz/global/config/SecurityConfig.java
  src/main/java/com/ajou/hertz/global/exception/constant/CustomExceptionType.java
  src/main/java/com/ajou/hertz/global/validator/Password.java
  src/main/java/com/ajou/hertz/global/validator/PasswordValidator.java
  src/test/java/com/ajou/hertz/config/ControllerTestConfig.java
  src/test/java/com/ajou/hertz/config/TestSecurityConfig.java
  src/test/java/com/ajou/hertz/unit/domain/user/controller/UserControllerV1Test.java
  src/test/java/com/ajou/hertz/unit/domain/user/service/UserCommandServiceTest.java
  src/test/java/com/ajou/hertz/unit/domain/user/service/UserQueryServiceTest.java
Labels: enhancement

#11 Validation error 발생 시 수행하는 API 응답 로직 수정
  src/main/java/com/ajou/hertz/global/exception/GlobalExceptionHandler.java
  src/main/java/com/ajou/hertz/global/exception/constant/GlobalExceptionType.java
  src/main/java/com/ajou/hertz/global/exception/constant/ValidationErrorCode.java
  src/main/java/com/ajou/hertz/global/exception/dto/response/ValidationErrorDetailResponse.java
  src/main/java/com/ajou/hertz/global/exception/util/ViolationMessageResolver.java
Labels: bug

#12 이메일로 회원 존재 여부 조회하기 API 구현
  src/main/java/com/ajou/hertz/domain/user/controller/UserControllerV1.java
  src/main/java/com/ajou/hertz/domain/user/dto/response/UserExistenceResponse.java
  src/main/java/com/ajou/hertz/global/config/SecurityConfig.java
  src/test/java/com/ajou/hertz/unit/domain/user/controller/UserControllerV1Test.java
Labels: enhancement

#14 Jacoco 도입 및 test coverage 설정
  build.gradle
Labels: chore

#15 회원가입 API 구현
  src/main/java/com/ajou/hertz/domain/user/controller/UserControllerV1.java
  src/main/java/com/ajou/hertz/domain/user/dto/request/SignUpRequest.java
  src/main/java/com/ajou/hertz/domain/user/entity/User.java
  src/main/java/com/ajou/hertz/domain/user/service/UserCommandService.java
  src/main/java/com/ajou/hertz/global/exception/constant/GlobalExceptionType.java
  src/main/java/com/ajou/hertz/global/validator/PhoneNumber.java
  src/main/java/com/ajou/hertz/global/validator/PhoneNumberValidator.java
  src/test/java/com/ajou/hertz/unit/domain/user/controller/UserControllerV1Test.java
  src/test/java/com/ajou/hertz/unit/domain/user/service/UserCommandServiceTest.java
Labels: enhancement

#18 AWS S3 파일 업로드 기능 구현
  build.gradle
  src/main/java/com/ajou/hertz/common/config/AmazonS3Config.java
  src/main/java/com/ajou/hertz/common/entity/FileEntity.java
  src/main/java/com/ajou/hertz/common/exception/MultipartFileNotReadableException.java
  src/main/java/com/ajou/hertz/common/exception/constant/CustomExceptionType.java
  src/main/java/com/ajou/hertz/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/ajou/hertz/common/file/dto/FileDto.java
  src/main/java/com/ajou/hertz/common/file/service/AmazonS3FileService.java
  src/main/java/com/ajou/hertz/common/file/service/FileService.java
  src/main/java/com/ajou/hertz/common/properties/AWSProperties.java
  src/main/resources/application.properties
  src/test/java/com/ajou/hertz/HertzApplicationTests.java
  src/test/java/com/ajou/hertz/unit/common/file/service/AmazonS3FileServiceTest.java
Labels: enhancement, chore

#20 임시 JPA Auditing 설정 - createdBy, updatedBy
  src/main/java/com/ajou/hertz/common/config/JpaConfig.java
Labels: chore

#27 자체 로그인 API 구현
  build.gradle
  src/main/java/com/ajou/hertz/common/auth/CustomUserDetailsService.java
  src/main/java/com/ajou/hertz/common/auth/JwtAccessDeniedHandler.java
  src/main/java/com/ajou/hertz/common/auth/JwtAuthenticationEntryPoint.java
  src/main/java/com/ajou/hertz/common/auth/JwtAuthenticationFilter.java
  src/main/java/com/ajou/hertz/common/auth/JwtExceptionFilter.java
  src/main/java/com/ajou/hertz/common/auth/JwtTokenProvider.java
  src/main/java/com/ajou/hertz/common/auth/UserPrincipal.java
  src/main/java/com/ajou/hertz/common/auth/controller/AuthControllerV1.java
  src/main/java/com/ajou/hertz/common/auth/dto/JwtTokenInfoDto.java
  src/main/java/com/ajou/hertz/common/auth/dto/request/LoginRequest.java
  src/main/java/com/ajou/hertz/common/auth/dto/response/JwtTokenInfoResponse.java
  src/main/java/com/ajou/hertz/common/auth/exception/PasswordMismatchException.java
  src/main/java/com/ajou/hertz/common/auth/exception/TokenValidateException.java
  src/main/java/com/ajou/hertz/common/auth/service/AuthService.java
  src/main/java/com/ajou/hertz/common/config/JpaConfig.java
  src/main/java/com/ajou/hertz/common/config/SecurityConfig.java
  src/main/java/com/ajou/hertz/common/exception/constant/CustomExceptionType.java
  src/main/java/com/ajou/hertz/common/properties/JwtProperties.java
  src/main/java/com/ajou/hertz/domain/user/constant/RoleType.java
  src/main/java/com/ajou/hertz/domain/user/converter/RoleTypesConverter.java
  src/main/java/com/ajou/hertz/domain/user/dto/UserDto.java
  src/main/java/com/ajou/hertz/domain/user/entity/User.java
  src/main/java/com/ajou/hertz/domain/user/exception/UserNotFoundByEmailException.java
  src/main/java/com/ajou/hertz/domain/user/exception/UserNotFoundByIdException.java
  src/main/java/com/ajou/hertz/domain/user/repository/UserRepository.java
  src/main/java/com/ajou/hertz/domain/user/service/UserQueryService.java
  src/main/resources/application.properties
  src/test/java/com/ajou/hertz/config/TestSecurityConfig.java
  src/test/java/com/ajou/hertz/unit/common/auth/controller/AuthControllerV1Test.java
  src/test/java/com/ajou/hertz/unit/common/auth/service/AuthServiceTest.java
  src/test/java/com/ajou/hertz/unit/domain/user/controller/UserControllerV1Test.java
  src/test/java/com/ajou/hertz/unit/domain/user/service/UserCommandServiceTest.java
  src/test/java/com/ajou/hertz/unit/domain/user/service/UserQueryServiceTest.java
Labels: enhancement

#29 서버의 timezone을 "Asia/Seoul"로 설정
  src/main/java/com/ajou/hertz/HertzApplication.java
Labels: chore

#31 유저 프로필 이미지 추가
  src/main/java/com/ajou/hertz/common/properties/HertzProperties.java
  src/main/java/com/ajou/hertz/domain/user/dto/UserDto.java
  src/main/java/com/ajou/hertz/domain/user/dto/response/UserResponse.java
  src/main/java/com/ajou/hertz/domain/user/entity/User.java
  src/main/java/com/ajou/hertz/domain/user/entity/UserProfileImage.java
  src/main/java/com/ajou/hertz/domain/user/service/UserCommandService.java
  src/main/resources/application.properties
  src/test/java/com/ajou/hertz/config/TestSecurityConfig.java
  src/test/java/com/ajou/hertz/unit/common/auth/service/AuthServiceTest.java
  src/test/java/com/ajou/hertz/unit/domain/user/controller/UserControllerV1Test.java
  src/test/java/com/ajou/hertz/unit/domain/user/service/UserCommandServiceTest.java
  src/test/java/com/ajou/hertz/unit/domain/user/service/UserQueryServiceTest.java
Labels: enhancement

#33 카카오 로그인 API 구현
  build.gradle
  src/main/java/com/ajou/hertz/common/auth/controller/AuthControllerV1.java
  src/main/java/com/ajou/hertz/common/auth/dto/request/KakaoLoginRequest.java
  src/main/java/com/ajou/hertz/common/config/SecurityConfig.java
  src/main/java/com/ajou/hertz/common/config/feign/FeignConfig.java
  src/main/java/com/ajou/hertz/common/config/feign/KakaoFeignConfig.java
  src/main/java/com/ajou/hertz/common/config/feign/KakaoFeignErrorDecoder.java
  src/main/java/com/ajou/hertz/common/exception/IOProcessingException.java
  src/main/java/com/ajou/hertz/common/exception/constant/CustomExceptionType.java
  src/main/java/com/ajou/hertz/common/kakao/client/KakaoAuthClient.java
  src/main/java/com/ajou/hertz/common/kakao/client/KakaoClient.java
  src/main/java/com/ajou/hertz/common/kakao/dto/request/IssueKakaoAccessTokenRequest.java
  src/main/java/com/ajou/hertz/common/kakao/dto/response/KakaoErrorResponse.java
  src/main/java/com/ajou/hertz/common/kakao/dto/response/KakaoTokenResponse.java
  src/main/java/com/ajou/hertz/common/kakao/dto/response/KakaoUserInfoResponse.java
  src/main/java/com/ajou/hertz/common/kakao/exception/KakaoClientException.java
  src/main/java/com/ajou/hertz/common/kakao/service/KakaoService.java
  src/main/java/com/ajou/hertz/common/properties/KakaoProperties.java
  src/main/java/com/ajou/hertz/domain/user/controller/UserControllerV1.java
  src/main/java/com/ajou/hertz/domain/user/dto/request/SignUpRequest.java
  src/main/java/com/ajou/hertz/domain/user/entity/User.java
  src/main/java/com/ajou/hertz/domain/user/exception/UserKakaoUidDuplicationException.java
  src/main/java/com/ajou/hertz/domain/user/exception/UserNotFoundByKakaoUidException.java
  src/main/java/com/ajou/hertz/domain/user/exception/UserPhoneDuplicationException.java
  src/main/java/com/ajou/hertz/domain/user/repository/UserRepository.java
  src/main/java/com/ajou/hertz/domain/user/service/UserCommandService.java
  src/main/java/com/ajou/hertz/domain/user/service/UserQueryService.java
  src/main/resources/application.properties
  src/test/java/com/ajou/hertz/unit/common/auth/controller/AuthControllerV1Test.java
  src/test/java/com/ajou/hertz/unit/common/kakao/service/KakaoServiceTest.java
  src/test/java/com/ajou/hertz/unit/domain/user/service/UserCommandServiceTest.java
  src/test/java/com/ajou/hertz/unit/domain/user/service/UserQueryServiceTest.java
Labels: enhancement

#43 악기 브랜드,모델 엔티티 생성
  src/main/java/com/ajou/hertz/domain/instrument/entity/InstrumentBrand.java
  src/main/java/com/ajou/hertz/domain/instrument/entity/InstrumentModel.java
Labels: enhancement

#45 내 정보 조회 API 구현
  src/main/java/com/ajou/hertz/domain/user/controller/UserControllerV1.java
  src/main/java/com/ajou/hertz/domain/user/dto/UserDto.java
  src/main/java/com/ajou/hertz/domain/user/dto/response/UserResponse.java
  src/main/java/com/ajou/hertz/domain/user/dto/response/UserWithLinkedAccountInfoResponse.java
  src/test/java/com/ajou/hertz/config/TestSecurityConfig.java
  src/test/java/com/ajou/hertz/unit/common/auth/service/AuthServiceTest.java
  src/test/java/com/ajou/hertz/unit/common/kakao/service/KakaoServiceTest.java
  src/test/java/com/ajou/hertz/unit/domain/user/controller/UserControllerV1Test.java
Labels: enhancement

#48 악기 관련 entity 구현
  src/main/java/com/ajou/hertz/common/entity/Address.java
  src/main/java/com/ajou/hertz/domain/instrument/constant/AcousticAndClassGuitarBrand.java
  src/main/java/com/ajou/hertz/domain/instrument/constant/AcousticAndClassGuitarModel.java
  src/main/java/com/ajou/hertz/domain/instrument/constant/AcousticAndClassGuitarPickUp.java
  src/main/java/com/ajou/hertz/domain/instrument/constant/AcousticAndClassGuitarWood.java
  src/main/java/com/ajou/hertz/domain/instrument/constant/AmplifierBrand.java
  src/main/java/com/ajou/hertz/domain/instrument/constant/AmplifierType.java
  src/main/java/com/ajou/hertz/domain/instrument/constant/AmplifierUsage.java
  src/main/java/com/ajou/hertz/domain/instrument/constant/AudioEquipmentType.java
  src/main/java/com/ajou/hertz/domain/instrument/constant/BassGuitarBrand.java
  src/main/java/com/ajou/hertz/domain/instrument/constant/BassGuitarPickUp.java
  src/main/java/com/ajou/hertz/domain/instrument/constant/BassGuitarPreAmplifier.java
  src/main/java/com/ajou/hertz/domain/instrument/constant/EffectorFeature.java
  src/main/java/com/ajou/hertz/domain/instrument/constant/EffectorType.java
  src/main/java/com/ajou/hertz/domain/instrument/constant/ElectricGuitarBrand.java
  src/main/java/com/ajou/hertz/domain/instrument/constant/ElectricGuitarModel.java
  src/main/java/com/ajou/hertz/domain/instrument/constant/GuitarColor.java
  src/main/java/com/ajou/hertz/domain/instrument/constant/InstrumentCategory.java
  src/main/java/com/ajou/hertz/domain/instrument/constant/InstrumentProgressStatus.java
  src/main/java/com/ajou/hertz/domain/instrument/constant/ProductOrigin.java
  src/main/java/com/ajou/hertz/domain/instrument/entity/AcousticAndClassGuitar.java
  src/main/java/com/ajou/hertz/domain/instrument/entity/Amplifier.java
  src/main/java/com/ajou/hertz/domain/instrument/entity/AudioEquipment.java
  src/main/java/com/ajou/hertz/domain/instrument/entity/BassGuitar.java
  src/main/java/com/ajou/hertz/domain/instrument/entity/Effector.java
  src/main/java/com/ajou/hertz/domain/instrument/entity/ElectricGuitar.java
  src/main/java/com/ajou/hertz/domain/instrument/entity/Instrument.java
  src/main/java/com/ajou/hertz/domain/instrument/entity/InstrumentHashtag.java
  src/main/java/com/ajou/hertz/domain/instrument/entity/InstrumentImage.java
Labels: enhancement

#51 일렉 기타 매물 생성 API 구현
  src/main/java/com/ajou/hertz/common/dto/AddressDto.java
  src/main/java/com/ajou/hertz/common/dto/request/AddressRequest.java
  src/main/java/com/ajou/hertz/common/dto/response/AddressResponse.java
  src/main/java/com/ajou/hertz/common/entity/Address.java
  src/main/java/com/ajou/hertz/domain/instrument/constant/InstrumentCategory.java
  src/main/java/com/ajou/hertz/domain/instrument/controller/InstrumentControllerV1.java
  src/main/java/com/ajou/hertz/domain/instrument/dto/ElectricGuitarDto.java
  src/main/java/com/ajou/hertz/domain/instrument/dto/InstrumentImageDto.java
  src/main/java/com/ajou/hertz/domain/instrument/dto/request/CreateNewElectricGuitarRequest.java
  src/main/java/com/ajou/hertz/domain/instrument/dto/response/ElectricGuitarResponse.java
  src/main/java/com/ajou/hertz/domain/instrument/dto/response/InstrumentImageResponse.java
  src/main/java/com/ajou/hertz/domain/instrument/entity/AcousticAndClassGuitar.java
  src/main/java/com/ajou/hertz/domain/instrument/entity/Amplifier.java
  src/main/java/com/ajou/hertz/domain/instrument/entity/AudioEquipment.java
  src/main/java/com/ajou/hertz/domain/instrument/entity/BassGuitar.java
  src/main/java/com/ajou/hertz/domain/instrument/entity/Effector.java
  src/main/java/com/ajou/hertz/domain/instrument/entity/ElectricGuitar.java
  src/main/java/com/ajou/hertz/domain/instrument/entity/Instrument.java
  src/main/java/com/ajou/hertz/domain/instrument/entity/InstrumentHashtag.java
  src/main/java/com/ajou/hertz/domain/instrument/entity/InstrumentHashtags.java
  src/main/java/com/ajou/hertz/domain/instrument/entity/InstrumentImage.java
  src/main/java/com/ajou/hertz/domain/instrument/entity/InstrumentImages.java
  src/main/java/com/ajou/hertz/domain/instrument/repository/InstrumentHashtagRepository.java
  src/main/java/com/ajou/hertz/domain/instrument/repository/InstrumentImageRepository.java
  src/main/java/com/ajou/hertz/domain/instrument/repository/InstrumentRepository.java
  src/main/java/com/ajou/hertz/domain/instrument/service/InstrumentCommandService.java
  src/main/java/com/ajou/hertz/domain/user/service/UserQueryService.java
  src/main/resources/application.properties
  src/test/java/com/ajou/hertz/unit/domain/instrument/controller/InstrumentControllerV1Test.java
  src/test/java/com/ajou/hertz/unit/domain/instrument/service/InstrumentCommandServiceTest.java
Labels: enhancement

#56 어쿠스틱&클래식 기타 매물 생성 API 구현
  src/main/java/com/ajou/hertz/domain/instrument/constant/AcousticAndClassicGuitarBrand.java
  src/main/java/com/ajou/hertz/domain/instrument/constant/AcousticAndClassicGuitarModel.java
  src/main/java/com/ajou/hertz/domain/instrument/constant/AcousticAndClassicGuitarPickUp.java
  src/main/java/com/ajou/hertz/domain/instrument/constant/AcousticAndClassicGuitarWood.java
  src/main/java/com/ajou/hertz/domain/instrument/controller/InstrumentControllerV1.java
  src/main/java/com/ajou/hertz/domain/instrument/dto/AcousticAndClassicGuitarDto.java
  src/main/java/com/ajou/hertz/domain/instrument/dto/request/CreateNewAcousticAndClassicGuitarRequest.java
  src/main/java/com/ajou/hertz/domain/instrument/dto/response/AcousticAndClassicGuitarResponse.java
  src/main/java/com/ajou/hertz/domain/instrument/dto/response/BassGuitarResponse.java
  src/main/java/com/ajou/hertz/domain/instrument/entity/AcousticAndClassicGuitar.java
  src/main/java/com/ajou/hertz/domain/instrument/service/InstrumentCommandService.java
  src/main/java/com/ajou/hertz/domain/instrument/strategy/AcousticAndClassicGuitarCreationStrategy.java
  src/test/java/com/ajou/hertz/unit/domain/instrument/controller/InstrumentControllerV1Test.java
  src/test/java/com/ajou/hertz/unit/domain/instrument/service/InstrumentCommandServiceTest.java
Labels: enhancement

#57 중고 악기 매물 생성 API 구현
  src/main/java/com/ajou/hertz/domain/instrument/controller/InstrumentControllerV1.java
  src/main/java/com/ajou/hertz/domain/instrument/dto/AmplifierDto.java
  src/main/java/com/ajou/hertz/domain/instrument/dto/AudioEquipmentDto.java
  src/main/java/com/ajou/hertz/domain/instrument/dto/EffectorDto.java
  src/main/java/com/ajou/hertz/domain/instrument/dto/request/CreateNewAmplifierRequest.java
  src/main/java/com/ajou/hertz/domain/instrument/dto/request/CreateNewAudioEquipmentRequest.java
  src/main/java/com/ajou/hertz/domain/instrument/dto/request/CreateNewEffectorRequest.java
  src/main/java/com/ajou/hertz/domain/instrument/dto/request/CreateNewInstrumentRequest.java
  src/main/java/com/ajou/hertz/domain/instrument/dto/response/AcousticAndClassicGuitarResponse.java
  src/main/java/com/ajou/hertz/domain/instrument/dto/response/AmplifierResponse.java
  src/main/java/com/ajou/hertz/domain/instrument/dto/response/AudioEquipmentResponse.java
  src/main/java/com/ajou/hertz/domain/instrument/dto/response/EffectorResponse.java
  src/main/java/com/ajou/hertz/domain/instrument/entity/Amplifier.java
  src/main/java/com/ajou/hertz/domain/instrument/service/InstrumentCommandService.java
  src/main/java/com/ajou/hertz/domain/instrument/strategy/AmplifierCreationStrategy.java
  src/main/java/com/ajou/hertz/domain/instrument/strategy/AudioEquipmentCreationStrategy.java
  src/main/java/com/ajou/hertz/domain/instrument/strategy/EffectorCreationStrategy.java
  src/test/java/com/ajou/hertz/unit/domain/instrument/controller/InstrumentControllerV1Test.java
  src/test/java/com/ajou/hertz/unit/domain/instrument/service/InstrumentCommandServiceTest.java
Labels: enhancement

#59 JAXB 경고 문구 대응
  build.gradle
Labels: chore

#61 API endpoint에 `/api` prefix 추가
  src/main/java/com/ajou/hertz/common/auth/controller/AuthControllerV1.java
  src/main/java/com/ajou/hertz/common/config/SecurityConfig.java
  src/main/java/com/ajou/hertz/domain/instrument/controller/InstrumentControllerV1.java
  src/main/java/com/ajou/hertz/domain/user/controller/UserControllerV1.java
  src/test/java/com/ajou/hertz/unit/common/auth/controller/AuthControllerV1Test.java
  src/test/java/com/ajou/hertz/unit/domain/instrument/controller/InstrumentControllerV1Test.java
  src/test/java/com/ajou/hertz/unit/domain/user/controller/UserControllerV1Test.java
Labels: enhancement

#53 행정 구역 API 구현
  src/main/java/com/ajou/hertz/common/config/SecurityConfig.java
  src/main/java/com/ajou/hertz/domain/administrative_area/controller/AdministrativeAreaControllerV1.java
  src/main/java/com/ajou/hertz/domain/administrative_area/dto/AdministrativeAreaDto.java
  src/main/java/com/ajou/hertz/domain/administrative_area/dto/response/AdministrativeAreaListResponse.java
  src/main/java/com/ajou/hertz/domain/administrative_area/dto/response/AdministrativeAreaResponse.java
  src/main/java/com/ajou/hertz/domain/administrative_area/entity/AdministrativeAreaEmd.java
  src/main/java/com/ajou/hertz/domain/administrative_area/entity/AdministrativeAreaSgg.java
  src/main/java/com/ajou/hertz/domain/administrative_area/entity/AdministrativeAreaSido.java
  src/main/java/com/ajou/hertz/domain/administrative_area/repository/AdministrativeEmdRepository.java
  src/main/java/com/ajou/hertz/domain/administrative_area/repository/AdministrativeSggRepository.java
  src/main/java/com/ajou/hertz/domain/administrative_area/repository/AdministrativeSidoRepository.java
  src/test/java/com/ajou/hertz/unit/domain/administrative_area/controller/AdministrativeAreaControllerV1Test.java
Labels: enhancement
